import Header from './Header';
import Head from 'next/head';
import Footer from './Footer';
import styles from '../styles/Home.module.css';
import { BodyStyled } from './styledcomponents/BodyStyled';
import { MainStyle } from './styledcomponents/MainStyle';

const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>Gold Chinchilla</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<BodyStyled>
				<Header />
				<MainStyle>{children}</MainStyle>
				<Footer />
			</BodyStyled>
		</>
	);
};

export default Layout;
